#!/bin/sh

# A single command to prepare the master branch for development

# cd to project root
root=$(git rev-parse --show-toplevel)
if [[ "$root" != $(pwd) ]]; then
cd "$root"
fi

git stash

git checkout master

# pull, supporting upstream
if git remote | grep upstream > /dev/null 2>&1; then
git fetch upstream -p \
&& git reset --hard upstream/master \
&& git push
else
git pull -p
fi

# delete merged branches
git branch --merged | grep -v "\*" | xargs -n 1 git branch -d;

# prune all remotes
for remote in $(git remote); do
git remote prune $remote
done

# update submodules, if applicable
if [[ -s .gitmodules ]]; then
git submodule update --init --recursive
fi

# optimize git
git gc

# display remaining branches, with details
git branch -vvv
